#!/usr/bin/env bash
#
# Generated by: https://openapi-generator.tech
#

dotnet restore src/Microservices/ && \
    dotnet build src/Microservices/ && \
    echo "Now, run the following to start the project: dotnet run -p src/Microservices/Microservices.csproj --launch-profile web"
