/*
 * Email Verification API
 *
 * This API verifies the validity, risk, and deliverability of an email address. 
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 * Generated by: https://openapi-generator.tech
 */

using System;
using System.Linq;
using System.Text;
using System.Collections.Generic;
using System.ComponentModel;
using System.ComponentModel.DataAnnotations;
using System.Runtime.Serialization;
using Newtonsoft.Json;
using Microservices.Converters;

namespace Microservices.Models
{ 
    
    /// <summary>
    /// An object containing phone numbers associated with the email address.
    /// </summary>
    [DataContract]
    public partial class EmailVerificationResponseIdentityDataPhoneNumbers : IEquatable<EmailVerificationResponseIdentityDataPhoneNumbers>
    {
        /// <summary>
        /// The full phone number, including country code.
        /// </summary>
        /// <value>The full phone number, including country code.</value>

        [DataMember(Name="formattedPhoneNumber", EmitDefaultValue=false)]


        public string FormattedPhoneNumber { get; set; }

        /// <summary>
        /// The country associated with the phone number.
        /// </summary>
        /// <value>The country associated with the phone number.</value>

        [DataMember(Name="country", EmitDefaultValue=false)]


        public string Country { get; set; }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            var sb = new StringBuilder();
            sb.Append("class EmailVerificationResponseIdentityDataPhoneNumbers {\n");
            sb.Append("  FormattedPhoneNumber: ").Append(FormattedPhoneNumber).Append("\n");
            sb.Append("  Country: ").Append(Country).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }

        /// <summary>
        /// Returns the JSON string presentation of the object
        /// </summary>
        /// <returns>JSON string presentation of the object</returns>
        public string ToJson()
        {
            return JsonConvert.SerializeObject(this, Formatting.Indented);
        }

        /// <summary>
        /// Returns true if objects are equal
        /// </summary>
        /// <param name="obj">Object to be compared</param>
        /// <returns>Boolean</returns>
        public override bool Equals(object obj)
        {
            if (obj is null) return false;
            if (ReferenceEquals(this, obj)) return true;
            return obj.GetType() == GetType() && Equals((EmailVerificationResponseIdentityDataPhoneNumbers)obj);
        }

        /// <summary>
        /// Returns true if EmailVerificationResponseIdentityDataPhoneNumbers instances are equal
        /// </summary>
        /// <param name="other">Instance of EmailVerificationResponseIdentityDataPhoneNumbers to be compared</param>
        /// <returns>Boolean</returns>
        public bool Equals(EmailVerificationResponseIdentityDataPhoneNumbers other)
        {
            if (other is null) return false;
            if (ReferenceEquals(this, other)) return true;

            return 
                (
                    FormattedPhoneNumber == other.FormattedPhoneNumber ||
                    FormattedPhoneNumber != null &&
                    FormattedPhoneNumber.Equals(other.FormattedPhoneNumber)
                ) && 
                (
                    Country == other.Country ||
                    Country != null &&
                    Country.Equals(other.Country)
                );
        }

        /// <summary>
        /// Gets the hash code
        /// </summary>
        /// <returns>Hash code</returns>
        public override int GetHashCode()
        {
            unchecked // Overflow is fine, just wrap
            {
                var hashCode = 41;
                // Suitable nullity checks etc, of course :)
                    if (FormattedPhoneNumber != null)
                    hashCode = hashCode * 59 + FormattedPhoneNumber.GetHashCode();
                    if (Country != null)
                    hashCode = hashCode * 59 + Country.GetHashCode();
                return hashCode;
            }
        }

        #region Operators
        #pragma warning disable 1591

        public static bool operator ==(EmailVerificationResponseIdentityDataPhoneNumbers left, EmailVerificationResponseIdentityDataPhoneNumbers right)
        {
            return Equals(left, right);
        }

        public static bool operator !=(EmailVerificationResponseIdentityDataPhoneNumbers left, EmailVerificationResponseIdentityDataPhoneNumbers right)
        {
            return !Equals(left, right);
        }

        #pragma warning restore 1591
        #endregion Operators
    }
}