/*
 * Email Verification API
 *
 * This API verifies the validity, risk, and deliverability of an email address. 
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 * Generated by: https://openapi-generator.tech
 */

using System;
using System.Linq;
using System.Text;
using System.Collections.Generic;
using System.ComponentModel;
using System.ComponentModel.DataAnnotations;
using System.Runtime.Serialization;
using Newtonsoft.Json;
using Microservices.Converters;

namespace Microservices.Models
{ 
    
    /// <summary>
    /// Names associated with the email address (may require higher subscription).
    /// </summary>
    [DataContract]
    public partial class EmailVerificationResponseAssociatedNames : IEquatable<EmailVerificationResponseAssociatedNames>
    {
        /// <summary>
        /// Status of data availability (e.g., \&quot;Enterprise Plus or higher required.\&quot;).
        /// </summary>
        /// <value>Status of data availability (e.g., \&quot;Enterprise Plus or higher required.\&quot;).</value>

        [DataMember(Name="status", EmitDefaultValue=false)]


        public string Status { get; set; }

        /// <summary>
        /// List of associated names.
        /// </summary>
        /// <value>List of associated names.</value>

        [DataMember(Name="names", EmitDefaultValue=false)]


        public List<string> Names { get; set; }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            var sb = new StringBuilder();
            sb.Append("class EmailVerificationResponseAssociatedNames {\n");
            sb.Append("  Status: ").Append(Status).Append("\n");
            sb.Append("  Names: ").Append(Names).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }

        /// <summary>
        /// Returns the JSON string presentation of the object
        /// </summary>
        /// <returns>JSON string presentation of the object</returns>
        public string ToJson()
        {
            return JsonConvert.SerializeObject(this, Formatting.Indented);
        }

        /// <summary>
        /// Returns true if objects are equal
        /// </summary>
        /// <param name="obj">Object to be compared</param>
        /// <returns>Boolean</returns>
        public override bool Equals(object obj)
        {
            if (obj is null) return false;
            if (ReferenceEquals(this, obj)) return true;
            return obj.GetType() == GetType() && Equals((EmailVerificationResponseAssociatedNames)obj);
        }

        /// <summary>
        /// Returns true if EmailVerificationResponseAssociatedNames instances are equal
        /// </summary>
        /// <param name="other">Instance of EmailVerificationResponseAssociatedNames to be compared</param>
        /// <returns>Boolean</returns>
        public bool Equals(EmailVerificationResponseAssociatedNames other)
        {
            if (other is null) return false;
            if (ReferenceEquals(this, other)) return true;

            return 
                (
                    Status == other.Status ||
                    Status != null &&
                    Status.Equals(other.Status)
                ) && 
                (
                    Names == other.Names ||
                    Names != null &&
                    other.Names != null &&
                    Names.SequenceEqual(other.Names)
                );
        }

        /// <summary>
        /// Gets the hash code
        /// </summary>
        /// <returns>Hash code</returns>
        public override int GetHashCode()
        {
            unchecked // Overflow is fine, just wrap
            {
                var hashCode = 41;
                // Suitable nullity checks etc, of course :)
                    if (Status != null)
                    hashCode = hashCode * 59 + Status.GetHashCode();
                    if (Names != null)
                    hashCode = hashCode * 59 + Names.GetHashCode();
                return hashCode;
            }
        }

        #region Operators
        #pragma warning disable 1591

        public static bool operator ==(EmailVerificationResponseAssociatedNames left, EmailVerificationResponseAssociatedNames right)
        {
            return Equals(left, right);
        }

        public static bool operator !=(EmailVerificationResponseAssociatedNames left, EmailVerificationResponseAssociatedNames right)
        {
            return !Equals(left, right);
        }

        #pragma warning restore 1591
        #endregion Operators
    }
}