/*
 * Email Verification API (IPQS)
 *
 * This API verifies the validity, risk, and deliverability of an email address using IPQS. 
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 * Generated by: https://openapi-generator.tech
 */

using System;
using System.Linq;
using System.Text;
using System.Collections.Generic;
using System.ComponentModel;
using System.ComponentModel.DataAnnotations;
using System.Runtime.Serialization;
using Newtonsoft.Json;
using Microservices.Converters;

namespace Microservices.Models
{ 
    /// <summary>
    /// When this email was first detected by the service.
    /// </summary>
    [DataContract]
    public partial class EmailVerificationResponseFirstSeen : IEquatable<EmailVerificationResponseFirstSeen>
    {
        /// <summary>
        /// Human-readable representation of when first seen.
        /// </summary>
        /// <value>Human-readable representation of when first seen.</value>
        [DataMember(Name="human", EmitDefaultValue=false)]
        public string Human { get; set; }

        /// <summary>
        /// Unix timestamp of when first seen.
        /// </summary>
        /// <value>Unix timestamp of when first seen.</value>
        [DataMember(Name="timestamp", EmitDefaultValue=true)]
        public int Timestamp { get; set; }

        /// <summary>
        /// ISO 8601 date/time of when first seen.
        /// </summary>
        /// <value>ISO 8601 date/time of when first seen.</value>
        [DataMember(Name="iso", EmitDefaultValue=true)]
        public DateTime Iso { get; set; }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            var sb = new StringBuilder();
            sb.Append("class EmailVerificationResponseFirstSeen {\n");
            sb.Append("  Human: ").Append(Human).Append("\n");
            sb.Append("  Timestamp: ").Append(Timestamp).Append("\n");
            sb.Append("  Iso: ").Append(Iso).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }

        /// <summary>
        /// Returns the JSON string presentation of the object
        /// </summary>
        /// <returns>JSON string presentation of the object</returns>
        public string ToJson()
        {
            return JsonConvert.SerializeObject(this, Formatting.Indented);
        }

        /// <summary>
        /// Returns true if objects are equal
        /// </summary>
        /// <param name="obj">Object to be compared</param>
        /// <returns>Boolean</returns>
        public override bool Equals(object obj)
        {
            if (obj is null) return false;
            if (ReferenceEquals(this, obj)) return true;
            return obj.GetType() == GetType() && Equals((EmailVerificationResponseFirstSeen)obj);
        }

        /// <summary>
        /// Returns true if EmailVerificationResponseFirstSeen instances are equal
        /// </summary>
        /// <param name="other">Instance of EmailVerificationResponseFirstSeen to be compared</param>
        /// <returns>Boolean</returns>
        public bool Equals(EmailVerificationResponseFirstSeen other)
        {
            if (other is null) return false;
            if (ReferenceEquals(this, other)) return true;

            return 
                (
                    Human == other.Human ||
                    Human != null &&
                    Human.Equals(other.Human)
                ) && 
                (
                    Timestamp == other.Timestamp ||
                    
                    Timestamp.Equals(other.Timestamp)
                ) && 
                (
                    Iso == other.Iso ||
                    
                    Iso.Equals(other.Iso)
                );
        }

        /// <summary>
        /// Gets the hash code
        /// </summary>
        /// <returns>Hash code</returns>
        public override int GetHashCode()
        {
            unchecked // Overflow is fine, just wrap
            {
                var hashCode = 41;
                // Suitable nullity checks etc, of course :)
                    if (Human != null)
                    hashCode = hashCode * 59 + Human.GetHashCode();
                    
                    hashCode = hashCode * 59 + Timestamp.GetHashCode();
                    
                    hashCode = hashCode * 59 + Iso.GetHashCode();
                return hashCode;
            }
        }

        #region Operators
        #pragma warning disable 1591

        public static bool operator ==(EmailVerificationResponseFirstSeen left, EmailVerificationResponseFirstSeen right)
        {
            return Equals(left, right);
        }

        public static bool operator !=(EmailVerificationResponseFirstSeen left, EmailVerificationResponseFirstSeen right)
        {
            return !Equals(left, right);
        }

        #pragma warning restore 1591
        #endregion Operators
    }
}
