/*
 * Email Verification API
 *
 * This API verifies the validity, risk, and deliverability of an email address. 
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 * Generated by: https://openapi-generator.tech
 */

using System;
using System.Linq;
using System.Text;
using System.Collections.Generic;
using System.ComponentModel;
using System.ComponentModel.DataAnnotations;
using System.Runtime.Serialization;
using Newtonsoft.Json;
using Microservices.Converters;

namespace Microservices.Models
{ 
    
    /// <summary>
    /// Identity and enrichment information associated with the email address.
    /// </summary>
    [DataContract]
    public partial class EmailVerificationResponseIdentityData : IEquatable<EmailVerificationResponseIdentityData>
    {
        /// <summary>
        /// Gets or Sets Names
        /// </summary>

        [DataMember(Name="names", EmitDefaultValue=false)]


        public EmailVerificationResponseIdentityDataNames Names { get; set; }

        /// <summary>
        /// Gets or Sets Addresses
        /// </summary>

        [DataMember(Name="addresses", EmitDefaultValue=false)]


        public EmailVerificationResponseIdentityDataAddresses Addresses { get; set; }

        /// <summary>
        /// Gets or Sets EmailAddresses
        /// </summary>

        [DataMember(Name="emailAddresses", EmitDefaultValue=false)]


        public EmailVerificationResponseIdentityDataEmailAddresses EmailAddresses { get; set; }

        /// <summary>
        /// Gets or Sets PhoneNumbers
        /// </summary>

        [DataMember(Name="phoneNumbers", EmitDefaultValue=false)]


        public EmailVerificationResponseIdentityDataPhoneNumbers PhoneNumbers { get; set; }

        /// <summary>
        /// Gets or Sets Age
        /// </summary>

        [DataMember(Name="age", EmitDefaultValue=false)]


        public EmailVerificationResponseIdentityDataAge Age { get; set; }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            var sb = new StringBuilder();
            sb.Append("class EmailVerificationResponseIdentityData {\n");
            sb.Append("  Names: ").Append(Names).Append("\n");
            sb.Append("  Addresses: ").Append(Addresses).Append("\n");
            sb.Append("  EmailAddresses: ").Append(EmailAddresses).Append("\n");
            sb.Append("  PhoneNumbers: ").Append(PhoneNumbers).Append("\n");
            sb.Append("  Age: ").Append(Age).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }

        /// <summary>
        /// Returns the JSON string presentation of the object
        /// </summary>
        /// <returns>JSON string presentation of the object</returns>
        public string ToJson()
        {
            return JsonConvert.SerializeObject(this, Formatting.Indented);
        }

        /// <summary>
        /// Returns true if objects are equal
        /// </summary>
        /// <param name="obj">Object to be compared</param>
        /// <returns>Boolean</returns>
        public override bool Equals(object obj)
        {
            if (obj is null) return false;
            if (ReferenceEquals(this, obj)) return true;
            return obj.GetType() == GetType() && Equals((EmailVerificationResponseIdentityData)obj);
        }

        /// <summary>
        /// Returns true if EmailVerificationResponseIdentityData instances are equal
        /// </summary>
        /// <param name="other">Instance of EmailVerificationResponseIdentityData to be compared</param>
        /// <returns>Boolean</returns>
        public bool Equals(EmailVerificationResponseIdentityData other)
        {
            if (other is null) return false;
            if (ReferenceEquals(this, other)) return true;

            return 
                (
                    Names == other.Names ||
                    Names != null &&
                    Names.Equals(other.Names)
                ) && 
                (
                    Addresses == other.Addresses ||
                    Addresses != null &&
                    Addresses.Equals(other.Addresses)
                ) && 
                (
                    EmailAddresses == other.EmailAddresses ||
                    EmailAddresses != null &&
                    EmailAddresses.Equals(other.EmailAddresses)
                ) && 
                (
                    PhoneNumbers == other.PhoneNumbers ||
                    PhoneNumbers != null &&
                    PhoneNumbers.Equals(other.PhoneNumbers)
                ) && 
                (
                    Age == other.Age ||
                    Age != null &&
                    Age.Equals(other.Age)
                );
        }

        /// <summary>
        /// Gets the hash code
        /// </summary>
        /// <returns>Hash code</returns>
        public override int GetHashCode()
        {
            unchecked // Overflow is fine, just wrap
            {
                var hashCode = 41;
                // Suitable nullity checks etc, of course :)
                    if (Names != null)
                    hashCode = hashCode * 59 + Names.GetHashCode();
                    if (Addresses != null)
                    hashCode = hashCode * 59 + Addresses.GetHashCode();
                    if (EmailAddresses != null)
                    hashCode = hashCode * 59 + EmailAddresses.GetHashCode();
                    if (PhoneNumbers != null)
                    hashCode = hashCode * 59 + PhoneNumbers.GetHashCode();
                    if (Age != null)
                    hashCode = hashCode * 59 + Age.GetHashCode();
                return hashCode;
            }
        }

        #region Operators
        #pragma warning disable 1591

        public static bool operator ==(EmailVerificationResponseIdentityData left, EmailVerificationResponseIdentityData right)
        {
            return Equals(left, right);
        }

        public static bool operator !=(EmailVerificationResponseIdentityData left, EmailVerificationResponseIdentityData right)
        {
            return !Equals(left, right);
        }

        #pragma warning restore 1591
        #endregion Operators
    }
}