/*
 * Email Verification API
 *
 * This API verifies the validity, risk, and deliverability of an email address. 
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 * Generated by: https://openapi-generator.tech
 */

using System;
using System.Linq;
using System.Text;
using System.Collections.Generic;
using System.ComponentModel;
using System.ComponentModel.DataAnnotations;
using System.Runtime.Serialization;
using Newtonsoft.Json;
using Microservices.Converters;

namespace Microservices.Models
{ 
    
    /// <summary>
    /// 
    /// </summary>
    [DataContract]
    public partial class EmailVerificationResponse : IEquatable<EmailVerificationResponse>
    {
        /// <summary>
        /// Indicates if the email address is valid (true/false).
        /// </summary>
        /// <value>Indicates if the email address is valid (true/false).</value>

        [DataMember(Name="valid", EmitDefaultValue=true)]


        public bool Valid { get; set; }

        /// <summary>
        /// True if the email server did not respond within the expected time.
        /// </summary>
        /// <value>True if the email server did not respond within the expected time.</value>

        [DataMember(Name="timedOut", EmitDefaultValue=true)]


        public bool TimedOut { get; set; }

        /// <summary>
        /// True if the email is from a temporary/disposable email provider.
        /// </summary>
        /// <value>True if the email is from a temporary/disposable email provider.</value>

        [DataMember(Name="disposable", EmitDefaultValue=true)]


        public bool Disposable { get; set; }

        /// <summary>
        /// First name associated with the email address, if available.
        /// </summary>
        /// <value>First name associated with the email address, if available.</value>

        [DataMember(Name="firstName", EmitDefaultValue=false)]


        public string FirstName { get; set; }


        /// <summary>
        /// Likelihood that emails will be delivered to this address (e.g., high, medium, low).
        /// </summary>
        /// <value>Likelihood that emails will be delivered to this address (e.g., high, medium, low).</value>
        [TypeConverter(typeof(CustomEnumConverter<DeliverabilityEnum>))]
        [JsonConverter(typeof(Newtonsoft.Json.Converters.StringEnumConverter))]
        public enum DeliverabilityEnum
        {
            
            /// <summary>
            /// Enum High for high
            /// </summary>
            [EnumMember(Value = "high")]
            High = 1,
            
            /// <summary>
            /// Enum Medium for medium
            /// </summary>
            [EnumMember(Value = "medium")]
            Medium = 2,
            
            /// <summary>
            /// Enum Low for low
            /// </summary>
            [EnumMember(Value = "low")]
            Low = 3
        }

        /// <summary>
        /// Likelihood that emails will be delivered to this address (e.g., high, medium, low).
        /// </summary>
        /// <value>Likelihood that emails will be delivered to this address (e.g., high, medium, low).</value>

        [DataMember(Name="deliverability", EmitDefaultValue=true)]


        public DeliverabilityEnum Deliverability { get; set; }

        /// <summary>
        /// Numeric score showing how well the email server responds to SMTP checks.
        /// </summary>
        /// <value>Numeric score showing how well the email server responds to SMTP checks.</value>

        [Range(-1, 3)]
        [DataMember(Name="smtpScore", EmitDefaultValue=true)]


        public int SmtpScore { get; set; }

        /// <summary>
        /// General risk score for the email address, typically lower is better.
        /// </summary>
        /// <value>General risk score for the email address, typically lower is better.</value>

        [Range(0, 4)]
        [DataMember(Name="overallScore", EmitDefaultValue=true)]


        public int OverallScore { get; set; }

        /// <summary>
        /// True if the domain is a &#39;catch-all&#39; and accepts all emails sent to it.
        /// </summary>
        /// <value>True if the domain is a &#39;catch-all&#39; and accepts all emails sent to it.</value>

        [DataMember(Name="catchAll", EmitDefaultValue=true)]


        public bool CatchAll { get; set; }

        /// <summary>
        /// True if the email is a generic address (e.g., info@, support@).
        /// </summary>
        /// <value>True if the email is a generic address (e.g., info@, support@).</value>

        [DataMember(Name="generic", EmitDefaultValue=true)]


        public bool Generic { get; set; }

        /// <summary>
        /// True if the email address is common or frequently used.
        /// </summary>
        /// <value>True if the email address is common or frequently used.</value>

        [DataMember(Name="common", EmitDefaultValue=true)]


        public bool Common { get; set; }

        /// <summary>
        /// True if the domain has valid DNS records for email.
        /// </summary>
        /// <value>True if the domain has valid DNS records for email.</value>

        [DataMember(Name="dnsValid", EmitDefaultValue=true)]


        public bool DnsValid { get; set; }

        /// <summary>
        /// True if the email is identified as a spam trap/honeypot.
        /// </summary>
        /// <value>True if the email is identified as a spam trap/honeypot.</value>

        [DataMember(Name="honeypot", EmitDefaultValue=true)]


        public bool Honeypot { get; set; }

        /// <summary>
        /// True if this address is known to frequently mark emails as spam.
        /// </summary>
        /// <value>True if this address is known to frequently mark emails as spam.</value>

        [DataMember(Name="frequentComplainer", EmitDefaultValue=true)]


        public bool FrequentComplainer { get; set; }

        /// <summary>
        /// True if the email is suspected to be risky, fraudulent, or problematic.
        /// </summary>
        /// <value>True if the email is suspected to be risky, fraudulent, or problematic.</value>

        [DataMember(Name="suspect", EmitDefaultValue=true)]


        public bool Suspect { get; set; }

        /// <summary>
        /// True if the email has recently been involved in abuse or spam activity.
        /// </summary>
        /// <value>True if the email has recently been involved in abuse or spam activity.</value>

        [DataMember(Name="recentAbuse", EmitDefaultValue=true)]


        public bool RecentAbuse { get; set; }

        /// <summary>
        /// Gets or Sets IdentityData
        /// </summary>

        [DataMember(Name="identityData", EmitDefaultValue=false)]


        public EmailVerificationResponseIdentityData IdentityData { get; set; }

        /// <summary>
        /// Numeric score (usually 0-100) representing the risk of fraud for this email.
        /// </summary>
        /// <value>Numeric score (usually 0-100) representing the risk of fraud for this email.</value>

        [Range(0, 100)]
        [DataMember(Name="fraudScore", EmitDefaultValue=true)]


        public int FraudScore { get; set; }

        /// <summary>
        /// True if this email address has appeared in data leaks or breaches.
        /// </summary>
        /// <value>True if this email address has appeared in data leaks or breaches.</value>

        [DataMember(Name="leaked", EmitDefaultValue=true)]


        public bool Leaked { get; set; }

        /// <summary>
        /// Alternative domain suggestion if the original domain might be a typo.
        /// </summary>
        /// <value>Alternative domain suggestion if the original domain might be a typo.</value>

        [DataMember(Name="suggestedDomain", EmitDefaultValue=false)]


        public string SuggestedDomain { get; set; }


        /// <summary>
        /// Indicates how quickly the domain is being used/registered (e.g., high for many new accounts at once).
        /// </summary>
        /// <value>Indicates how quickly the domain is being used/registered (e.g., high for many new accounts at once).</value>
        [TypeConverter(typeof(CustomEnumConverter<DomainVelocityEnum>))]
        [JsonConverter(typeof(Newtonsoft.Json.Converters.StringEnumConverter))]
        public enum DomainVelocityEnum
        {
            
            /// <summary>
            /// Enum High for high
            /// </summary>
            [EnumMember(Value = "high")]
            High = 1,
            
            /// <summary>
            /// Enum Medium for medium
            /// </summary>
            [EnumMember(Value = "medium")]
            Medium = 2,
            
            /// <summary>
            /// Enum Low for low
            /// </summary>
            [EnumMember(Value = "low")]
            Low = 3,
            
            /// <summary>
            /// Enum None for none
            /// </summary>
            [EnumMember(Value = "none")]
            None = 4
        }

        /// <summary>
        /// Indicates how quickly the domain is being used/registered (e.g., high for many new accounts at once).
        /// </summary>
        /// <value>Indicates how quickly the domain is being used/registered (e.g., high for many new accounts at once).</value>

        [DataMember(Name="domainVelocity", EmitDefaultValue=true)]


        public DomainVelocityEnum DomainVelocity { get; set; }


        /// <summary>
        /// Level of trust for the domain (e.g., trusted, untrusted).
        /// </summary>
        /// <value>Level of trust for the domain (e.g., trusted, untrusted).</value>
        [TypeConverter(typeof(CustomEnumConverter<DomainTrustEnum>))]
        [JsonConverter(typeof(Newtonsoft.Json.Converters.StringEnumConverter))]
        public enum DomainTrustEnum
        {
            
            /// <summary>
            /// Enum Trusted for trusted
            /// </summary>
            [EnumMember(Value = "trusted")]
            Trusted = 1,
            
            /// <summary>
            /// Enum Positive for positive
            /// </summary>
            [EnumMember(Value = "positive")]
            Positive = 2,
            
            /// <summary>
            /// Enum Neutral for neutral
            /// </summary>
            [EnumMember(Value = "neutral")]
            Neutral = 3,
            
            /// <summary>
            /// Enum Suspicious for suspicious
            /// </summary>
            [EnumMember(Value = "suspicious")]
            Suspicious = 4,
            
            /// <summary>
            /// Enum Malicious for malicious
            /// </summary>
            [EnumMember(Value = "malicious")]
            Malicious = 5,
            
            /// <summary>
            /// Enum NotRated for notRated
            /// </summary>
            [EnumMember(Value = "notRated")]
            NotRated = 6
        }

        /// <summary>
        /// Level of trust for the domain (e.g., trusted, untrusted).
        /// </summary>
        /// <value>Level of trust for the domain (e.g., trusted, untrusted).</value>

        [DataMember(Name="domainTrust", EmitDefaultValue=true)]


        public DomainTrustEnum DomainTrust { get; set; }


        /// <summary>
        /// Level of past user activity associated with this email (high, medium, low).
        /// </summary>
        /// <value>Level of past user activity associated with this email (high, medium, low).</value>
        [TypeConverter(typeof(CustomEnumConverter<UserActivityEnum>))]
        [JsonConverter(typeof(Newtonsoft.Json.Converters.StringEnumConverter))]
        public enum UserActivityEnum
        {
            
            /// <summary>
            /// Enum High for high
            /// </summary>
            [EnumMember(Value = "high")]
            High = 1,
            
            /// <summary>
            /// Enum Medium for medium
            /// </summary>
            [EnumMember(Value = "medium")]
            Medium = 2,
            
            /// <summary>
            /// Enum Low for low
            /// </summary>
            [EnumMember(Value = "low")]
            Low = 3,
            
            /// <summary>
            /// Enum None for none
            /// </summary>
            [EnumMember(Value = "none")]
            None = 4
        }

        /// <summary>
        /// Level of past user activity associated with this email (high, medium, low).
        /// </summary>
        /// <value>Level of past user activity associated with this email (high, medium, low).</value>

        [DataMember(Name="userActivity", EmitDefaultValue=true)]


        public UserActivityEnum UserActivity { get; set; }

        /// <summary>
        /// Gets or Sets AssociatedNames
        /// </summary>

        [DataMember(Name="associatedNames", EmitDefaultValue=false)]


        public EmailVerificationResponseAssociatedNames AssociatedNames { get; set; }

        /// <summary>
        /// Gets or Sets AssociatedPhoneNumbers
        /// </summary>

        [DataMember(Name="associatedPhoneNumbers", EmitDefaultValue=false)]


        public EmailVerificationResponseAssociatedPhoneNumbers AssociatedPhoneNumbers { get; set; }

        /// <summary>
        /// Gets or Sets FirstSeen
        /// </summary>

        [DataMember(Name="firstSeen", EmitDefaultValue=false)]


        public EmailVerificationResponseFirstSeen FirstSeen { get; set; }

        /// <summary>
        /// Gets or Sets DomainAge
        /// </summary>

        [DataMember(Name="domainAge", EmitDefaultValue=false)]


        public EmailVerificationResponseDomainAge DomainAge { get; set; }

        /// <summary>
        /// True if the API request was completed successfully.
        /// </summary>
        /// <value>True if the API request was completed successfully.</value>

        [DataMember(Name="success", EmitDefaultValue=true)]


        public bool Success { get; set; }


        /// <summary>
        /// Indicates spam trap risk (e.g., none, low, medium, high).
        /// </summary>
        /// <value>Indicates spam trap risk (e.g., none, low, medium, high).</value>
        [TypeConverter(typeof(CustomEnumConverter<SpamTrapScoreEnum>))]
        [JsonConverter(typeof(Newtonsoft.Json.Converters.StringEnumConverter))]
        public enum SpamTrapScoreEnum
        {
            
            /// <summary>
            /// Enum High for high
            /// </summary>
            [EnumMember(Value = "high")]
            High = 1,
            
            /// <summary>
            /// Enum Medium for medium
            /// </summary>
            [EnumMember(Value = "medium")]
            Medium = 2,
            
            /// <summary>
            /// Enum Low for low
            /// </summary>
            [EnumMember(Value = "low")]
            Low = 3,
            
            /// <summary>
            /// Enum None for none
            /// </summary>
            [EnumMember(Value = "none")]
            None = 4
        }

        /// <summary>
        /// Indicates spam trap risk (e.g., none, low, medium, high).
        /// </summary>
        /// <value>Indicates spam trap risk (e.g., none, low, medium, high).</value>

        [DataMember(Name="spamTrapScore", EmitDefaultValue=true)]


        public SpamTrapScoreEnum SpamTrapScore { get; set; }

        /// <summary>
        /// True if the top-level domain (TLD) is considered risky (e.g., .xyz, .top).
        /// </summary>
        /// <value>True if the top-level domain (TLD) is considered risky (e.g., .xyz, .top).</value>

        [DataMember(Name="riskyTld", EmitDefaultValue=true)]


        public bool RiskyTld { get; set; }

        /// <summary>
        /// True if the domain has a valid SPF (Sender Policy Framework) record.
        /// </summary>
        /// <value>True if the domain has a valid SPF (Sender Policy Framework) record.</value>

        [DataMember(Name="spfRecord", EmitDefaultValue=true)]


        public bool SpfRecord { get; set; }

        /// <summary>
        /// True if the domain has a valid DMARC record.
        /// </summary>
        /// <value>True if the domain has a valid DMARC record.</value>

        [DataMember(Name="dmarcRecord", EmitDefaultValue=true)]


        public bool DmarcRecord { get; set; }

        /// <summary>
        /// The standardized/cleaned version of the input email address.
        /// </summary>
        /// <value>The standardized/cleaned version of the input email address.</value>

        [DataMember(Name="sanitizedEmail", EmitDefaultValue=false)]


        public string SanitizedEmail { get; set; }

        /// <summary>
        /// List of mail exchange (MX) servers for the domain.
        /// </summary>
        /// <value>List of mail exchange (MX) servers for the domain.</value>

        [DataMember(Name="mxRecords", EmitDefaultValue=false)]


        public List<string> MxRecords { get; set; }

        /// <summary>
        /// Unique identifier for this API request, useful for troubleshooting.
        /// </summary>
        /// <value>Unique identifier for this API request, useful for troubleshooting.</value>

        [DataMember(Name="requestId", EmitDefaultValue=false)]


        public string RequestId { get; set; }

        /// <summary>
        /// List of A (address) records for the domain, representing IP addresses.
        /// </summary>
        /// <value>List of A (address) records for the domain, representing IP addresses.</value>

        [DataMember(Name="aRecords", EmitDefaultValue=false)]


        public List<string> ARecords { get; set; }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            var sb = new StringBuilder();
            sb.Append("class EmailVerificationResponse {\n");
            sb.Append("  Valid: ").Append(Valid).Append("\n");
            sb.Append("  TimedOut: ").Append(TimedOut).Append("\n");
            sb.Append("  Disposable: ").Append(Disposable).Append("\n");
            sb.Append("  FirstName: ").Append(FirstName).Append("\n");
            sb.Append("  Deliverability: ").Append(Deliverability).Append("\n");
            sb.Append("  SmtpScore: ").Append(SmtpScore).Append("\n");
            sb.Append("  OverallScore: ").Append(OverallScore).Append("\n");
            sb.Append("  CatchAll: ").Append(CatchAll).Append("\n");
            sb.Append("  Generic: ").Append(Generic).Append("\n");
            sb.Append("  Common: ").Append(Common).Append("\n");
            sb.Append("  DnsValid: ").Append(DnsValid).Append("\n");
            sb.Append("  Honeypot: ").Append(Honeypot).Append("\n");
            sb.Append("  FrequentComplainer: ").Append(FrequentComplainer).Append("\n");
            sb.Append("  Suspect: ").Append(Suspect).Append("\n");
            sb.Append("  RecentAbuse: ").Append(RecentAbuse).Append("\n");
            sb.Append("  IdentityData: ").Append(IdentityData).Append("\n");
            sb.Append("  FraudScore: ").Append(FraudScore).Append("\n");
            sb.Append("  Leaked: ").Append(Leaked).Append("\n");
            sb.Append("  SuggestedDomain: ").Append(SuggestedDomain).Append("\n");
            sb.Append("  DomainVelocity: ").Append(DomainVelocity).Append("\n");
            sb.Append("  DomainTrust: ").Append(DomainTrust).Append("\n");
            sb.Append("  UserActivity: ").Append(UserActivity).Append("\n");
            sb.Append("  AssociatedNames: ").Append(AssociatedNames).Append("\n");
            sb.Append("  AssociatedPhoneNumbers: ").Append(AssociatedPhoneNumbers).Append("\n");
            sb.Append("  FirstSeen: ").Append(FirstSeen).Append("\n");
            sb.Append("  DomainAge: ").Append(DomainAge).Append("\n");
            sb.Append("  Success: ").Append(Success).Append("\n");
            sb.Append("  SpamTrapScore: ").Append(SpamTrapScore).Append("\n");
            sb.Append("  RiskyTld: ").Append(RiskyTld).Append("\n");
            sb.Append("  SpfRecord: ").Append(SpfRecord).Append("\n");
            sb.Append("  DmarcRecord: ").Append(DmarcRecord).Append("\n");
            sb.Append("  SanitizedEmail: ").Append(SanitizedEmail).Append("\n");
            sb.Append("  MxRecords: ").Append(MxRecords).Append("\n");
            sb.Append("  RequestId: ").Append(RequestId).Append("\n");
            sb.Append("  ARecords: ").Append(ARecords).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }

        /// <summary>
        /// Returns the JSON string presentation of the object
        /// </summary>
        /// <returns>JSON string presentation of the object</returns>
        public string ToJson()
        {
            return JsonConvert.SerializeObject(this, Formatting.Indented);
        }

        /// <summary>
        /// Returns true if objects are equal
        /// </summary>
        /// <param name="obj">Object to be compared</param>
        /// <returns>Boolean</returns>
        public override bool Equals(object obj)
        {
            if (obj is null) return false;
            if (ReferenceEquals(this, obj)) return true;
            return obj.GetType() == GetType() && Equals((EmailVerificationResponse)obj);
        }

        /// <summary>
        /// Returns true if EmailVerificationResponse instances are equal
        /// </summary>
        /// <param name="other">Instance of EmailVerificationResponse to be compared</param>
        /// <returns>Boolean</returns>
        public bool Equals(EmailVerificationResponse other)
        {
            if (other is null) return false;
            if (ReferenceEquals(this, other)) return true;

            return 
                (
                    Valid == other.Valid ||
                    
                    Valid.Equals(other.Valid)
                ) && 
                (
                    TimedOut == other.TimedOut ||
                    
                    TimedOut.Equals(other.TimedOut)
                ) && 
                (
                    Disposable == other.Disposable ||
                    
                    Disposable.Equals(other.Disposable)
                ) && 
                (
                    FirstName == other.FirstName ||
                    FirstName != null &&
                    FirstName.Equals(other.FirstName)
                ) && 
                (
                    Deliverability == other.Deliverability ||
                    
                    Deliverability.Equals(other.Deliverability)
                ) && 
                (
                    SmtpScore == other.SmtpScore ||
                    
                    SmtpScore.Equals(other.SmtpScore)
                ) && 
                (
                    OverallScore == other.OverallScore ||
                    
                    OverallScore.Equals(other.OverallScore)
                ) && 
                (
                    CatchAll == other.CatchAll ||
                    
                    CatchAll.Equals(other.CatchAll)
                ) && 
                (
                    Generic == other.Generic ||
                    
                    Generic.Equals(other.Generic)
                ) && 
                (
                    Common == other.Common ||
                    
                    Common.Equals(other.Common)
                ) && 
                (
                    DnsValid == other.DnsValid ||
                    
                    DnsValid.Equals(other.DnsValid)
                ) && 
                (
                    Honeypot == other.Honeypot ||
                    
                    Honeypot.Equals(other.Honeypot)
                ) && 
                (
                    FrequentComplainer == other.FrequentComplainer ||
                    
                    FrequentComplainer.Equals(other.FrequentComplainer)
                ) && 
                (
                    Suspect == other.Suspect ||
                    
                    Suspect.Equals(other.Suspect)
                ) && 
                (
                    RecentAbuse == other.RecentAbuse ||
                    
                    RecentAbuse.Equals(other.RecentAbuse)
                ) && 
                (
                    IdentityData == other.IdentityData ||
                    IdentityData != null &&
                    IdentityData.Equals(other.IdentityData)
                ) && 
                (
                    FraudScore == other.FraudScore ||
                    
                    FraudScore.Equals(other.FraudScore)
                ) && 
                (
                    Leaked == other.Leaked ||
                    
                    Leaked.Equals(other.Leaked)
                ) && 
                (
                    SuggestedDomain == other.SuggestedDomain ||
                    SuggestedDomain != null &&
                    SuggestedDomain.Equals(other.SuggestedDomain)
                ) && 
                (
                    DomainVelocity == other.DomainVelocity ||
                    
                    DomainVelocity.Equals(other.DomainVelocity)
                ) && 
                (
                    DomainTrust == other.DomainTrust ||
                    
                    DomainTrust.Equals(other.DomainTrust)
                ) && 
                (
                    UserActivity == other.UserActivity ||
                    
                    UserActivity.Equals(other.UserActivity)
                ) && 
                (
                    AssociatedNames == other.AssociatedNames ||
                    AssociatedNames != null &&
                    AssociatedNames.Equals(other.AssociatedNames)
                ) && 
                (
                    AssociatedPhoneNumbers == other.AssociatedPhoneNumbers ||
                    AssociatedPhoneNumbers != null &&
                    AssociatedPhoneNumbers.Equals(other.AssociatedPhoneNumbers)
                ) && 
                (
                    FirstSeen == other.FirstSeen ||
                    FirstSeen != null &&
                    FirstSeen.Equals(other.FirstSeen)
                ) && 
                (
                    DomainAge == other.DomainAge ||
                    DomainAge != null &&
                    DomainAge.Equals(other.DomainAge)
                ) && 
                (
                    Success == other.Success ||
                    
                    Success.Equals(other.Success)
                ) && 
                (
                    SpamTrapScore == other.SpamTrapScore ||
                    
                    SpamTrapScore.Equals(other.SpamTrapScore)
                ) && 
                (
                    RiskyTld == other.RiskyTld ||
                    
                    RiskyTld.Equals(other.RiskyTld)
                ) && 
                (
                    SpfRecord == other.SpfRecord ||
                    
                    SpfRecord.Equals(other.SpfRecord)
                ) && 
                (
                    DmarcRecord == other.DmarcRecord ||
                    
                    DmarcRecord.Equals(other.DmarcRecord)
                ) && 
                (
                    SanitizedEmail == other.SanitizedEmail ||
                    SanitizedEmail != null &&
                    SanitizedEmail.Equals(other.SanitizedEmail)
                ) && 
                (
                    MxRecords == other.MxRecords ||
                    MxRecords != null &&
                    other.MxRecords != null &&
                    MxRecords.SequenceEqual(other.MxRecords)
                ) && 
                (
                    RequestId == other.RequestId ||
                    RequestId != null &&
                    RequestId.Equals(other.RequestId)
                ) && 
                (
                    ARecords == other.ARecords ||
                    ARecords != null &&
                    other.ARecords != null &&
                    ARecords.SequenceEqual(other.ARecords)
                );
        }

        /// <summary>
        /// Gets the hash code
        /// </summary>
        /// <returns>Hash code</returns>
        public override int GetHashCode()
        {
            unchecked // Overflow is fine, just wrap
            {
                var hashCode = 41;
                // Suitable nullity checks etc, of course :)
                    
                    hashCode = hashCode * 59 + Valid.GetHashCode();
                    
                    hashCode = hashCode * 59 + TimedOut.GetHashCode();
                    
                    hashCode = hashCode * 59 + Disposable.GetHashCode();
                    if (FirstName != null)
                    hashCode = hashCode * 59 + FirstName.GetHashCode();
                    
                    hashCode = hashCode * 59 + Deliverability.GetHashCode();
                    
                    hashCode = hashCode * 59 + SmtpScore.GetHashCode();
                    
                    hashCode = hashCode * 59 + OverallScore.GetHashCode();
                    
                    hashCode = hashCode * 59 + CatchAll.GetHashCode();
                    
                    hashCode = hashCode * 59 + Generic.GetHashCode();
                    
                    hashCode = hashCode * 59 + Common.GetHashCode();
                    
                    hashCode = hashCode * 59 + DnsValid.GetHashCode();
                    
                    hashCode = hashCode * 59 + Honeypot.GetHashCode();
                    
                    hashCode = hashCode * 59 + FrequentComplainer.GetHashCode();
                    
                    hashCode = hashCode * 59 + Suspect.GetHashCode();
                    
                    hashCode = hashCode * 59 + RecentAbuse.GetHashCode();
                    if (IdentityData != null)
                    hashCode = hashCode * 59 + IdentityData.GetHashCode();
                    
                    hashCode = hashCode * 59 + FraudScore.GetHashCode();
                    
                    hashCode = hashCode * 59 + Leaked.GetHashCode();
                    if (SuggestedDomain != null)
                    hashCode = hashCode * 59 + SuggestedDomain.GetHashCode();
                    
                    hashCode = hashCode * 59 + DomainVelocity.GetHashCode();
                    
                    hashCode = hashCode * 59 + DomainTrust.GetHashCode();
                    
                    hashCode = hashCode * 59 + UserActivity.GetHashCode();
                    if (AssociatedNames != null)
                    hashCode = hashCode * 59 + AssociatedNames.GetHashCode();
                    if (AssociatedPhoneNumbers != null)
                    hashCode = hashCode * 59 + AssociatedPhoneNumbers.GetHashCode();
                    if (FirstSeen != null)
                    hashCode = hashCode * 59 + FirstSeen.GetHashCode();
                    if (DomainAge != null)
                    hashCode = hashCode * 59 + DomainAge.GetHashCode();
                    
                    hashCode = hashCode * 59 + Success.GetHashCode();
                    
                    hashCode = hashCode * 59 + SpamTrapScore.GetHashCode();
                    
                    hashCode = hashCode * 59 + RiskyTld.GetHashCode();
                    
                    hashCode = hashCode * 59 + SpfRecord.GetHashCode();
                    
                    hashCode = hashCode * 59 + DmarcRecord.GetHashCode();
                    if (SanitizedEmail != null)
                    hashCode = hashCode * 59 + SanitizedEmail.GetHashCode();
                    if (MxRecords != null)
                    hashCode = hashCode * 59 + MxRecords.GetHashCode();
                    if (RequestId != null)
                    hashCode = hashCode * 59 + RequestId.GetHashCode();
                    if (ARecords != null)
                    hashCode = hashCode * 59 + ARecords.GetHashCode();
                return hashCode;
            }
        }

        #region Operators
        #pragma warning disable 1591

        public static bool operator ==(EmailVerificationResponse left, EmailVerificationResponse right)
        {
            return Equals(left, right);
        }

        public static bool operator !=(EmailVerificationResponse left, EmailVerificationResponse right)
        {
            return !Equals(left, right);
        }

        #pragma warning restore 1591
        #endregion Operators
    }
}