/*
 * Email Verification API
 *
 * This API verifies the validity, risk, and deliverability of an email address. 
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 * Generated by: https://openapi-generator.tech
 */

using System;
using System.Linq;
using System.Text;
using System.Collections.Generic;
using System.ComponentModel;
using System.ComponentModel.DataAnnotations;
using System.Runtime.Serialization;
using Newtonsoft.Json;
using Microservices.Converters;

namespace Microservices.Models
{ 
    
    /// <summary>
    /// 
    /// </summary>
    [DataContract]
    public partial class EmailVerificationAPIResponse : IEquatable<EmailVerificationAPIResponse>
    {
        /// <summary>
        /// Gets or Sets ApiResponse
        /// </summary>

        [DataMember(Name="apiResponse", EmitDefaultValue=false)]


        public APIResponse ApiResponse { get; set; }

        /// <summary>
        /// Gets or Sets Result
        /// </summary>

        [DataMember(Name="result", EmitDefaultValue=false)]


        public EmailVerificationResponse Result { get; set; }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            var sb = new StringBuilder();
            sb.Append("class EmailVerificationAPIResponse {\n");
            sb.Append("  ApiResponse: ").Append(ApiResponse).Append("\n");
            sb.Append("  Result: ").Append(Result).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }

        /// <summary>
        /// Returns the JSON string presentation of the object
        /// </summary>
        /// <returns>JSON string presentation of the object</returns>
        public string ToJson()
        {
            return JsonConvert.SerializeObject(this, Formatting.Indented);
        }

        /// <summary>
        /// Returns true if objects are equal
        /// </summary>
        /// <param name="obj">Object to be compared</param>
        /// <returns>Boolean</returns>
        public override bool Equals(object obj)
        {
            if (obj is null) return false;
            if (ReferenceEquals(this, obj)) return true;
            return obj.GetType() == GetType() && Equals((EmailVerificationAPIResponse)obj);
        }

        /// <summary>
        /// Returns true if EmailVerificationAPIResponse instances are equal
        /// </summary>
        /// <param name="other">Instance of EmailVerificationAPIResponse to be compared</param>
        /// <returns>Boolean</returns>
        public bool Equals(EmailVerificationAPIResponse other)
        {
            if (other is null) return false;
            if (ReferenceEquals(this, other)) return true;

            return 
                (
                    ApiResponse == other.ApiResponse ||
                    ApiResponse != null &&
                    ApiResponse.Equals(other.ApiResponse)
                ) && 
                (
                    Result == other.Result ||
                    Result != null &&
                    Result.Equals(other.Result)
                );
        }

        /// <summary>
        /// Gets the hash code
        /// </summary>
        /// <returns>Hash code</returns>
        public override int GetHashCode()
        {
            unchecked // Overflow is fine, just wrap
            {
                var hashCode = 41;
                // Suitable nullity checks etc, of course :)
                    if (ApiResponse != null)
                    hashCode = hashCode * 59 + ApiResponse.GetHashCode();
                    if (Result != null)
                    hashCode = hashCode * 59 + Result.GetHashCode();
                return hashCode;
            }
        }

        #region Operators
        #pragma warning disable 1591

        public static bool operator ==(EmailVerificationAPIResponse left, EmailVerificationAPIResponse right)
        {
            return Equals(left, right);
        }

        public static bool operator !=(EmailVerificationAPIResponse left, EmailVerificationAPIResponse right)
        {
            return !Equals(left, right);
        }

        #pragma warning restore 1591
        #endregion Operators
    }
}