/*
 * Email Verification API (IPQS)
 *
 * This API verifies the validity, risk, and deliverability of an email address using IPQS. 
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 * Generated by: https://openapi-generator.tech
 */

using System;
using System.Linq;
using System.Text;
using System.Collections.Generic;
using System.ComponentModel;
using System.ComponentModel.DataAnnotations;
using System.Runtime.Serialization;
using Newtonsoft.Json;
using Microservices.Converters;

namespace Microservices.Models
{ 
    /// <summary>
    /// An object containing ages of people associated with the email address.
    /// </summary>
    [DataContract]
    public partial class EmailVerificationResponseIdentityDataAge : IEquatable<EmailVerificationResponseIdentityDataAge>
    {
        /// <summary>
        /// How many years old the person is.
        /// </summary>
        /// <value>How many years old the person is.</value>
        [DataMember(Name="human", EmitDefaultValue=true)]
        public int Human { get; set; }

        /// <summary>
        /// Their date of birth in ISO format.
        /// </summary>
        /// <value>Their date of birth in ISO format.</value>
        [DataMember(Name="birthdayIso", EmitDefaultValue=true)]
        public DateTime BirthdayIso { get; set; }

        /// <summary>
        /// Their birthday in timestamp format.
        /// </summary>
        /// <value>Their birthday in timestamp format.</value>
        [DataMember(Name="birthdayTimestamp", EmitDefaultValue=true)]
        public int BirthdayTimestamp { get; set; }

        /// <summary>
        /// Whether we are certain the birthdate is correct.
        /// </summary>
        /// <value>Whether we are certain the birthdate is correct.</value>
        [DataMember(Name="birthdateCertainty", EmitDefaultValue=true)]
        public bool BirthdateCertainty { get; set; }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            var sb = new StringBuilder();
            sb.Append("class EmailVerificationResponseIdentityDataAge {\n");
            sb.Append("  Human: ").Append(Human).Append("\n");
            sb.Append("  BirthdayIso: ").Append(BirthdayIso).Append("\n");
            sb.Append("  BirthdayTimestamp: ").Append(BirthdayTimestamp).Append("\n");
            sb.Append("  BirthdateCertainty: ").Append(BirthdateCertainty).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }

        /// <summary>
        /// Returns the JSON string presentation of the object
        /// </summary>
        /// <returns>JSON string presentation of the object</returns>
        public string ToJson()
        {
            return JsonConvert.SerializeObject(this, Formatting.Indented);
        }

        /// <summary>
        /// Returns true if objects are equal
        /// </summary>
        /// <param name="obj">Object to be compared</param>
        /// <returns>Boolean</returns>
        public override bool Equals(object obj)
        {
            if (obj is null) return false;
            if (ReferenceEquals(this, obj)) return true;
            return obj.GetType() == GetType() && Equals((EmailVerificationResponseIdentityDataAge)obj);
        }

        /// <summary>
        /// Returns true if EmailVerificationResponseIdentityDataAge instances are equal
        /// </summary>
        /// <param name="other">Instance of EmailVerificationResponseIdentityDataAge to be compared</param>
        /// <returns>Boolean</returns>
        public bool Equals(EmailVerificationResponseIdentityDataAge other)
        {
            if (other is null) return false;
            if (ReferenceEquals(this, other)) return true;

            return 
                (
                    Human == other.Human ||
                    
                    Human.Equals(other.Human)
                ) && 
                (
                    BirthdayIso == other.BirthdayIso ||
                    
                    BirthdayIso.Equals(other.BirthdayIso)
                ) && 
                (
                    BirthdayTimestamp == other.BirthdayTimestamp ||
                    
                    BirthdayTimestamp.Equals(other.BirthdayTimestamp)
                ) && 
                (
                    BirthdateCertainty == other.BirthdateCertainty ||
                    
                    BirthdateCertainty.Equals(other.BirthdateCertainty)
                );
        }

        /// <summary>
        /// Gets the hash code
        /// </summary>
        /// <returns>Hash code</returns>
        public override int GetHashCode()
        {
            unchecked // Overflow is fine, just wrap
            {
                var hashCode = 41;
                // Suitable nullity checks etc, of course :)
                    
                    hashCode = hashCode * 59 + Human.GetHashCode();
                    
                    hashCode = hashCode * 59 + BirthdayIso.GetHashCode();
                    
                    hashCode = hashCode * 59 + BirthdayTimestamp.GetHashCode();
                    
                    hashCode = hashCode * 59 + BirthdateCertainty.GetHashCode();
                return hashCode;
            }
        }

        #region Operators
        #pragma warning disable 1591

        public static bool operator ==(EmailVerificationResponseIdentityDataAge left, EmailVerificationResponseIdentityDataAge right)
        {
            return Equals(left, right);
        }

        public static bool operator !=(EmailVerificationResponseIdentityDataAge left, EmailVerificationResponseIdentityDataAge right)
        {
            return !Equals(left, right);
        }

        #pragma warning restore 1591
        #endregion Operators
    }
}
