/*
 * Email Verification API
 *
 * This API verifies the validity, risk, and deliverability of an email address. 
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 * Generated by: https://openapi-generator.tech
 */

using System;
using System.Linq;
using System.Text;
using System.Collections.Generic;
using System.ComponentModel;
using System.ComponentModel.DataAnnotations;
using System.Runtime.Serialization;
using Newtonsoft.Json;
using Microservices.Converters;

namespace Microservices.Models
{ 
    
    /// <summary>
    /// An object containing other email addresses associated with the email address.
    /// </summary>
    [DataContract]
    public partial class EmailVerificationResponseIdentityDataEmailAddresses : IEquatable<EmailVerificationResponseIdentityDataEmailAddresses>
    {
        /// <summary>
        /// The email address.
        /// </summary>
        /// <value>The email address.</value>

        [DataMember(Name="email", EmitDefaultValue=false)]


        public string Email { get; set; }

        /// <summary>
        /// When the email address was first created.
        /// </summary>
        /// <value>When the email address was first created.</value>

        [DataMember(Name="firstSeen", EmitDefaultValue=true)]


        public DateTime FirstSeen { get; set; }

        /// <summary>
        /// When the email address was last used.
        /// </summary>
        /// <value>When the email address was last used.</value>

        [DataMember(Name="lastSeen", EmitDefaultValue=true)]


        public DateTime LastSeen { get; set; }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            var sb = new StringBuilder();
            sb.Append("class EmailVerificationResponseIdentityDataEmailAddresses {\n");
            sb.Append("  Email: ").Append(Email).Append("\n");
            sb.Append("  FirstSeen: ").Append(FirstSeen).Append("\n");
            sb.Append("  LastSeen: ").Append(LastSeen).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }

        /// <summary>
        /// Returns the JSON string presentation of the object
        /// </summary>
        /// <returns>JSON string presentation of the object</returns>
        public string ToJson()
        {
            return JsonConvert.SerializeObject(this, Formatting.Indented);
        }

        /// <summary>
        /// Returns true if objects are equal
        /// </summary>
        /// <param name="obj">Object to be compared</param>
        /// <returns>Boolean</returns>
        public override bool Equals(object obj)
        {
            if (obj is null) return false;
            if (ReferenceEquals(this, obj)) return true;
            return obj.GetType() == GetType() && Equals((EmailVerificationResponseIdentityDataEmailAddresses)obj);
        }

        /// <summary>
        /// Returns true if EmailVerificationResponseIdentityDataEmailAddresses instances are equal
        /// </summary>
        /// <param name="other">Instance of EmailVerificationResponseIdentityDataEmailAddresses to be compared</param>
        /// <returns>Boolean</returns>
        public bool Equals(EmailVerificationResponseIdentityDataEmailAddresses other)
        {
            if (other is null) return false;
            if (ReferenceEquals(this, other)) return true;

            return 
                (
                    Email == other.Email ||
                    Email != null &&
                    Email.Equals(other.Email)
                ) && 
                (
                    FirstSeen == other.FirstSeen ||
                    
                    FirstSeen.Equals(other.FirstSeen)
                ) && 
                (
                    LastSeen == other.LastSeen ||
                    
                    LastSeen.Equals(other.LastSeen)
                );
        }

        /// <summary>
        /// Gets the hash code
        /// </summary>
        /// <returns>Hash code</returns>
        public override int GetHashCode()
        {
            unchecked // Overflow is fine, just wrap
            {
                var hashCode = 41;
                // Suitable nullity checks etc, of course :)
                    if (Email != null)
                    hashCode = hashCode * 59 + Email.GetHashCode();
                    
                    hashCode = hashCode * 59 + FirstSeen.GetHashCode();
                    
                    hashCode = hashCode * 59 + LastSeen.GetHashCode();
                return hashCode;
            }
        }

        #region Operators
        #pragma warning disable 1591

        public static bool operator ==(EmailVerificationResponseIdentityDataEmailAddresses left, EmailVerificationResponseIdentityDataEmailAddresses right)
        {
            return Equals(left, right);
        }

        public static bool operator !=(EmailVerificationResponseIdentityDataEmailAddresses left, EmailVerificationResponseIdentityDataEmailAddresses right)
        {
            return !Equals(left, right);
        }

        #pragma warning restore 1591
        #endregion Operators
    }
}