/*
 * Email Verification API
 *
 * This API verifies the validity, risk, and deliverability of an email address. 
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 * Generated by: https://openapi-generator.tech
 */

using System;
using System.Linq;
using System.Text;
using System.Collections.Generic;
using System.ComponentModel;
using System.ComponentModel.DataAnnotations;
using System.Runtime.Serialization;
using Newtonsoft.Json;
using Microservices.Converters;

namespace Microservices.Models
{ 
    
    /// <summary>
    /// 
    /// </summary>
    [DataContract]
    public partial class PhoneValidationRequest : IEquatable<PhoneValidationRequest>
    {
        /// <summary>
        /// Phone number to be verified.
        /// </summary>
        /// <value>Phone number to be verified.</value>
        [Required]
        [DataMember(Name="phoneNumber", EmitDefaultValue=false)]


        public string PhoneNumber { get; set; }

        /// <summary>
        /// (Optional) Country codes to validate against (e.g., [&#39;US&#39;, &#39;UK&#39;]).
        /// </summary>
        /// <value>(Optional) Country codes to validate against (e.g., [&#39;US&#39;, &#39;UK&#39;]).</value>

        [DataMember(Name="country", EmitDefaultValue=false)]


        public List<string> Country { get; set; }


        /// <summary>
        /// (Optional) Strictness level for validation (0 = normal, 1 = strictest).
        /// </summary>
        /// <value>(Optional) Strictness level for validation (0 = normal, 1 = strictest).</value>
        
        public enum StrictnessEnum
        {
            
            /// <summary>
            /// Enum _0 for 0
            /// </summary>
            
            _0 = 0,
            
            /// <summary>
            /// Enum _1 for 1
            /// </summary>
            
            _1 = 1
        }

        /// <summary>
        /// (Optional) Strictness level for validation (0 &#x3D; normal, 1 &#x3D; strictest).
        /// </summary>
        /// <value>(Optional) Strictness level for validation (0 &#x3D; normal, 1 &#x3D; strictest).</value>

        [DataMember(Name="strictness", EmitDefaultValue=true)]


        public StrictnessEnum Strictness { get; set; }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            var sb = new StringBuilder();
            sb.Append("class PhoneValidationRequest {\n");
            sb.Append("  PhoneNumber: ").Append(PhoneNumber).Append("\n");
            sb.Append("  Country: ").Append(Country).Append("\n");
            sb.Append("  Strictness: ").Append(Strictness).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }

        /// <summary>
        /// Returns the JSON string presentation of the object
        /// </summary>
        /// <returns>JSON string presentation of the object</returns>
        public string ToJson()
        {
            return JsonConvert.SerializeObject(this, Formatting.Indented);
        }

        /// <summary>
        /// Returns true if objects are equal
        /// </summary>
        /// <param name="obj">Object to be compared</param>
        /// <returns>Boolean</returns>
        public override bool Equals(object obj)
        {
            if (obj is null) return false;
            if (ReferenceEquals(this, obj)) return true;
            return obj.GetType() == GetType() && Equals((PhoneValidationRequest)obj);
        }

        /// <summary>
        /// Returns true if PhoneValidationRequest instances are equal
        /// </summary>
        /// <param name="other">Instance of PhoneValidationRequest to be compared</param>
        /// <returns>Boolean</returns>
        public bool Equals(PhoneValidationRequest other)
        {
            if (other is null) return false;
            if (ReferenceEquals(this, other)) return true;

            return 
                (
                    PhoneNumber == other.PhoneNumber ||
                    PhoneNumber != null &&
                    PhoneNumber.Equals(other.PhoneNumber)
                ) && 
                (
                    Country == other.Country ||
                    Country != null &&
                    other.Country != null &&
                    Country.SequenceEqual(other.Country)
                ) && 
                (
                    Strictness == other.Strictness ||
                    
                    Strictness.Equals(other.Strictness)
                );
        }

        /// <summary>
        /// Gets the hash code
        /// </summary>
        /// <returns>Hash code</returns>
        public override int GetHashCode()
        {
            unchecked // Overflow is fine, just wrap
            {
                var hashCode = 41;
                // Suitable nullity checks etc, of course :)
                    if (PhoneNumber != null)
                    hashCode = hashCode * 59 + PhoneNumber.GetHashCode();
                    if (Country != null)
                    hashCode = hashCode * 59 + Country.GetHashCode();
                    
                    hashCode = hashCode * 59 + Strictness.GetHashCode();
                return hashCode;
            }
        }

        #region Operators
        #pragma warning disable 1591

        public static bool operator ==(PhoneValidationRequest left, PhoneValidationRequest right)
        {
            return Equals(left, right);
        }

        public static bool operator !=(PhoneValidationRequest left, PhoneValidationRequest right)
        {
            return !Equals(left, right);
        }

        #pragma warning restore 1591
        #endregion Operators
    }
}