/*
 * Email Verification API
 *
 * This API verifies the validity, risk, and deliverability of an email address. 
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 * Generated by: https://openapi-generator.tech
 */

using System;
using System.Linq;
using System.Text;
using System.Collections.Generic;
using System.ComponentModel;
using System.ComponentModel.DataAnnotations;
using System.Runtime.Serialization;
using Newtonsoft.Json;
using Microservices.Converters;

namespace Microservices.Models
{ 
    
    /// <summary>
    /// 
    /// </summary>
    [DataContract]
    public partial class PhoneValidationResponse : IEquatable<PhoneValidationResponse>
    {
        /// <summary>
        /// Response message from the API.
        /// </summary>
        /// <value>Response message from the API.</value>

        [DataMember(Name="message", EmitDefaultValue=false)]


        public string Message { get; set; }

        /// <summary>
        /// Indicates if the request was successful.
        /// </summary>
        /// <value>Indicates if the request was successful.</value>

        [DataMember(Name="success", EmitDefaultValue=true)]


        public bool Success { get; set; }

        /// <summary>
        /// Formatted phone number in international format.
        /// </summary>
        /// <value>Formatted phone number in international format.</value>

        [DataMember(Name="formatted", EmitDefaultValue=false)]


        public string Formatted { get; set; }

        /// <summary>
        /// Phone number in local format.
        /// </summary>
        /// <value>Phone number in local format.</value>

        [DataMember(Name="local_format", EmitDefaultValue=false)]


        public string LocalFormat { get; set; }

        /// <summary>
        /// Whether the phone number is valid.
        /// </summary>
        /// <value>Whether the phone number is valid.</value>

        [DataMember(Name="valid", EmitDefaultValue=true)]


        public bool Valid { get; set; }

        /// <summary>
        /// Risk score (0-100, higher means riskier).
        /// </summary>
        /// <value>Risk score (0-100, higher means riskier).</value>

        [DataMember(Name="fraud_score", EmitDefaultValue=true)]


        public int FraudScore { get; set; }

        /// <summary>
        /// Whether there has been recent abuse from this number.
        /// </summary>
        /// <value>Whether there has been recent abuse from this number.</value>

        [DataMember(Name="recent_abuse", EmitDefaultValue=true)]


        public bool RecentAbuse { get; set; }

        /// <summary>
        /// Whether the phone number is a VOIP line.
        /// </summary>
        /// <value>Whether the phone number is a VOIP line.</value>

        [DataMember(Name="VOIP", EmitDefaultValue=true)]


        public bool VOIP { get; set; }

        /// <summary>
        /// Whether the number is prepaid.
        /// </summary>
        /// <value>Whether the number is prepaid.</value>

        [DataMember(Name="prepaid", EmitDefaultValue=true)]


        public bool Prepaid { get; set; }

        /// <summary>
        /// Whether the phone number is considered risky.
        /// </summary>
        /// <value>Whether the phone number is considered risky.</value>

        [DataMember(Name="risky", EmitDefaultValue=true)]


        public bool Risky { get; set; }

        /// <summary>
        /// Whether the phone number is currently active.
        /// </summary>
        /// <value>Whether the phone number is currently active.</value>

        [DataMember(Name="active", EmitDefaultValue=true)]


        public bool Active { get; set; }

        /// <summary>
        /// Name of the data provider.
        /// </summary>
        /// <value>Name of the data provider.</value>

        [DataMember(Name="name", EmitDefaultValue=false)]


        public string Name { get; set; }

        /// <summary>
        /// Carrier name.
        /// </summary>
        /// <value>Carrier name.</value>

        [DataMember(Name="carrier", EmitDefaultValue=false)]


        public string Carrier { get; set; }

        /// <summary>
        /// Type of phone line (e.g., mobile, landline, toll free).
        /// </summary>
        /// <value>Type of phone line (e.g., mobile, landline, toll free).</value>

        [DataMember(Name="line_type", EmitDefaultValue=false)]


        public string LineType { get; set; }

        /// <summary>
        /// Country code or name.
        /// </summary>
        /// <value>Country code or name.</value>

        [DataMember(Name="country", EmitDefaultValue=false)]


        public string Country { get; set; }

        /// <summary>
        /// Region or state.
        /// </summary>
        /// <value>Region or state.</value>

        [DataMember(Name="region", EmitDefaultValue=false)]


        public string Region { get; set; }

        /// <summary>
        /// City.
        /// </summary>
        /// <value>City.</value>

        [DataMember(Name="city", EmitDefaultValue=false)]


        public string City { get; set; }

        /// <summary>
        /// Timezone of the number.
        /// </summary>
        /// <value>Timezone of the number.</value>

        [DataMember(Name="timezone", EmitDefaultValue=false)]


        public string Timezone { get; set; }

        /// <summary>
        /// Zip or postal code.
        /// </summary>
        /// <value>Zip or postal code.</value>

        [DataMember(Name="zip_code", EmitDefaultValue=false)]


        public string ZipCode { get; set; }

        /// <summary>
        /// Indicates if the detected country code is accurate.
        /// </summary>
        /// <value>Indicates if the detected country code is accurate.</value>

        [DataMember(Name="accurate_country_code", EmitDefaultValue=true)]


        public bool AccurateCountryCode { get; set; }

        /// <summary>
        /// International dialing code.
        /// </summary>
        /// <value>International dialing code.</value>

        [DataMember(Name="dialing_code", EmitDefaultValue=true)]


        public int DialingCode { get; set; }

        /// <summary>
        /// Whether the number has been leaked.
        /// </summary>
        /// <value>Whether the number has been leaked.</value>

        [DataMember(Name="leaked", EmitDefaultValue=true)]


        public bool Leaked { get; set; }

        /// <summary>
        /// Whether the number is associated with spam.
        /// </summary>
        /// <value>Whether the number is associated with spam.</value>

        [DataMember(Name="spammer", EmitDefaultValue=true)]


        public bool Spammer { get; set; }

        /// <summary>
        /// Mobile Network Code.
        /// </summary>
        /// <value>Mobile Network Code.</value>

        [DataMember(Name="mnc", EmitDefaultValue=false)]


        public string Mnc { get; set; }

        /// <summary>
        /// Mobile Country Code.
        /// </summary>
        /// <value>Mobile Country Code.</value>

        [DataMember(Name="mcc", EmitDefaultValue=false)]


        public string Mcc { get; set; }

        /// <summary>
        /// Unique ID for the request.
        /// </summary>
        /// <value>Unique ID for the request.</value>

        [DataMember(Name="request_id", EmitDefaultValue=false)]


        public string RequestId { get; set; }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            var sb = new StringBuilder();
            sb.Append("class PhoneValidationResponse {\n");
            sb.Append("  Message: ").Append(Message).Append("\n");
            sb.Append("  Success: ").Append(Success).Append("\n");
            sb.Append("  Formatted: ").Append(Formatted).Append("\n");
            sb.Append("  LocalFormat: ").Append(LocalFormat).Append("\n");
            sb.Append("  Valid: ").Append(Valid).Append("\n");
            sb.Append("  FraudScore: ").Append(FraudScore).Append("\n");
            sb.Append("  RecentAbuse: ").Append(RecentAbuse).Append("\n");
            sb.Append("  VOIP: ").Append(VOIP).Append("\n");
            sb.Append("  Prepaid: ").Append(Prepaid).Append("\n");
            sb.Append("  Risky: ").Append(Risky).Append("\n");
            sb.Append("  Active: ").Append(Active).Append("\n");
            sb.Append("  Name: ").Append(Name).Append("\n");
            sb.Append("  Carrier: ").Append(Carrier).Append("\n");
            sb.Append("  LineType: ").Append(LineType).Append("\n");
            sb.Append("  Country: ").Append(Country).Append("\n");
            sb.Append("  Region: ").Append(Region).Append("\n");
            sb.Append("  City: ").Append(City).Append("\n");
            sb.Append("  Timezone: ").Append(Timezone).Append("\n");
            sb.Append("  ZipCode: ").Append(ZipCode).Append("\n");
            sb.Append("  AccurateCountryCode: ").Append(AccurateCountryCode).Append("\n");
            sb.Append("  DialingCode: ").Append(DialingCode).Append("\n");
            sb.Append("  Leaked: ").Append(Leaked).Append("\n");
            sb.Append("  Spammer: ").Append(Spammer).Append("\n");
            sb.Append("  Mnc: ").Append(Mnc).Append("\n");
            sb.Append("  Mcc: ").Append(Mcc).Append("\n");
            sb.Append("  RequestId: ").Append(RequestId).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }

        /// <summary>
        /// Returns the JSON string presentation of the object
        /// </summary>
        /// <returns>JSON string presentation of the object</returns>
        public string ToJson()
        {
            return JsonConvert.SerializeObject(this, Formatting.Indented);
        }

        /// <summary>
        /// Returns true if objects are equal
        /// </summary>
        /// <param name="obj">Object to be compared</param>
        /// <returns>Boolean</returns>
        public override bool Equals(object obj)
        {
            if (obj is null) return false;
            if (ReferenceEquals(this, obj)) return true;
            return obj.GetType() == GetType() && Equals((PhoneValidationResponse)obj);
        }

        /// <summary>
        /// Returns true if PhoneValidationResponse instances are equal
        /// </summary>
        /// <param name="other">Instance of PhoneValidationResponse to be compared</param>
        /// <returns>Boolean</returns>
        public bool Equals(PhoneValidationResponse other)
        {
            if (other is null) return false;
            if (ReferenceEquals(this, other)) return true;

            return 
                (
                    Message == other.Message ||
                    Message != null &&
                    Message.Equals(other.Message)
                ) && 
                (
                    Success == other.Success ||
                    
                    Success.Equals(other.Success)
                ) && 
                (
                    Formatted == other.Formatted ||
                    Formatted != null &&
                    Formatted.Equals(other.Formatted)
                ) && 
                (
                    LocalFormat == other.LocalFormat ||
                    LocalFormat != null &&
                    LocalFormat.Equals(other.LocalFormat)
                ) && 
                (
                    Valid == other.Valid ||
                    
                    Valid.Equals(other.Valid)
                ) && 
                (
                    FraudScore == other.FraudScore ||
                    
                    FraudScore.Equals(other.FraudScore)
                ) && 
                (
                    RecentAbuse == other.RecentAbuse ||
                    
                    RecentAbuse.Equals(other.RecentAbuse)
                ) && 
                (
                    VOIP == other.VOIP ||
                    
                    VOIP.Equals(other.VOIP)
                ) && 
                (
                    Prepaid == other.Prepaid ||
                    
                    Prepaid.Equals(other.Prepaid)
                ) && 
                (
                    Risky == other.Risky ||
                    
                    Risky.Equals(other.Risky)
                ) && 
                (
                    Active == other.Active ||
                    
                    Active.Equals(other.Active)
                ) && 
                (
                    Name == other.Name ||
                    Name != null &&
                    Name.Equals(other.Name)
                ) && 
                (
                    Carrier == other.Carrier ||
                    Carrier != null &&
                    Carrier.Equals(other.Carrier)
                ) && 
                (
                    LineType == other.LineType ||
                    LineType != null &&
                    LineType.Equals(other.LineType)
                ) && 
                (
                    Country == other.Country ||
                    Country != null &&
                    Country.Equals(other.Country)
                ) && 
                (
                    Region == other.Region ||
                    Region != null &&
                    Region.Equals(other.Region)
                ) && 
                (
                    City == other.City ||
                    City != null &&
                    City.Equals(other.City)
                ) && 
                (
                    Timezone == other.Timezone ||
                    Timezone != null &&
                    Timezone.Equals(other.Timezone)
                ) && 
                (
                    ZipCode == other.ZipCode ||
                    ZipCode != null &&
                    ZipCode.Equals(other.ZipCode)
                ) && 
                (
                    AccurateCountryCode == other.AccurateCountryCode ||
                    
                    AccurateCountryCode.Equals(other.AccurateCountryCode)
                ) && 
                (
                    DialingCode == other.DialingCode ||
                    
                    DialingCode.Equals(other.DialingCode)
                ) && 
                (
                    Leaked == other.Leaked ||
                    
                    Leaked.Equals(other.Leaked)
                ) && 
                (
                    Spammer == other.Spammer ||
                    
                    Spammer.Equals(other.Spammer)
                ) && 
                (
                    Mnc == other.Mnc ||
                    Mnc != null &&
                    Mnc.Equals(other.Mnc)
                ) && 
                (
                    Mcc == other.Mcc ||
                    Mcc != null &&
                    Mcc.Equals(other.Mcc)
                ) && 
                (
                    RequestId == other.RequestId ||
                    RequestId != null &&
                    RequestId.Equals(other.RequestId)
                );
        }

        /// <summary>
        /// Gets the hash code
        /// </summary>
        /// <returns>Hash code</returns>
        public override int GetHashCode()
        {
            unchecked // Overflow is fine, just wrap
            {
                var hashCode = 41;
                // Suitable nullity checks etc, of course :)
                    if (Message != null)
                    hashCode = hashCode * 59 + Message.GetHashCode();
                    
                    hashCode = hashCode * 59 + Success.GetHashCode();
                    if (Formatted != null)
                    hashCode = hashCode * 59 + Formatted.GetHashCode();
                    if (LocalFormat != null)
                    hashCode = hashCode * 59 + LocalFormat.GetHashCode();
                    
                    hashCode = hashCode * 59 + Valid.GetHashCode();
                    
                    hashCode = hashCode * 59 + FraudScore.GetHashCode();
                    
                    hashCode = hashCode * 59 + RecentAbuse.GetHashCode();
                    
                    hashCode = hashCode * 59 + VOIP.GetHashCode();
                    
                    hashCode = hashCode * 59 + Prepaid.GetHashCode();
                    
                    hashCode = hashCode * 59 + Risky.GetHashCode();
                    
                    hashCode = hashCode * 59 + Active.GetHashCode();
                    if (Name != null)
                    hashCode = hashCode * 59 + Name.GetHashCode();
                    if (Carrier != null)
                    hashCode = hashCode * 59 + Carrier.GetHashCode();
                    if (LineType != null)
                    hashCode = hashCode * 59 + LineType.GetHashCode();
                    if (Country != null)
                    hashCode = hashCode * 59 + Country.GetHashCode();
                    if (Region != null)
                    hashCode = hashCode * 59 + Region.GetHashCode();
                    if (City != null)
                    hashCode = hashCode * 59 + City.GetHashCode();
                    if (Timezone != null)
                    hashCode = hashCode * 59 + Timezone.GetHashCode();
                    if (ZipCode != null)
                    hashCode = hashCode * 59 + ZipCode.GetHashCode();
                    
                    hashCode = hashCode * 59 + AccurateCountryCode.GetHashCode();
                    
                    hashCode = hashCode * 59 + DialingCode.GetHashCode();
                    
                    hashCode = hashCode * 59 + Leaked.GetHashCode();
                    
                    hashCode = hashCode * 59 + Spammer.GetHashCode();
                    if (Mnc != null)
                    hashCode = hashCode * 59 + Mnc.GetHashCode();
                    if (Mcc != null)
                    hashCode = hashCode * 59 + Mcc.GetHashCode();
                    if (RequestId != null)
                    hashCode = hashCode * 59 + RequestId.GetHashCode();
                return hashCode;
            }
        }

        #region Operators
        #pragma warning disable 1591

        public static bool operator ==(PhoneValidationResponse left, PhoneValidationResponse right)
        {
            return Equals(left, right);
        }

        public static bool operator !=(PhoneValidationResponse left, PhoneValidationResponse right)
        {
            return !Equals(left, right);
        }

        #pragma warning restore 1591
        #endregion Operators
    }
}