/*
 * Email Verification API
 *
 * This API verifies the validity, risk, and deliverability of an email address. 
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 * Generated by: https://openapi-generator.tech
 */

using System;
using System.Linq;
using System.Text;
using System.Collections.Generic;
using System.ComponentModel;
using System.ComponentModel.DataAnnotations;
using System.Runtime.Serialization;
using Newtonsoft.Json;
using Microservices.Converters;

namespace Microservices.Models
{ 
    
    /// <summary>
    /// 
    /// </summary>
    [DataContract]
    public partial class ProxyAndVpnDetectionResponse : IEquatable<ProxyAndVpnDetectionResponse>
    {
        /// <summary>
        /// Gets or Sets Message
        /// </summary>
        /* <example>Success.</example> */

        [DataMember(Name="message", EmitDefaultValue=false)]

        [DefaultValue("Success.")]

        public string Message { get; set; } = "Success.";

        /// <summary>
        /// Gets or Sets Success
        /// </summary>
        /* <example>true</example> */

        [DataMember(Name="success", EmitDefaultValue=true)]

        [DefaultValue(true)]

        public bool Success { get; set; } = true;

        /// <summary>
        /// Gets or Sets FraudScore
        /// </summary>
        /* <example>25</example> */

        [DataMember(Name="fraudScore", EmitDefaultValue=true)]

        [DefaultValue(25)]

        public int FraudScore { get; set; } = 25;

        /// <summary>
        /// Gets or Sets Proxy
        /// </summary>
        /* <example>false</example> */

        [DataMember(Name="proxy", EmitDefaultValue=true)]

        [DefaultValue(false)]

        public bool Proxy { get; set; } = false;

        /// <summary>
        /// Gets or Sets ISP
        /// </summary>
        /* <example>Mediacom Cable</example> */

        [DataMember(Name="ISP", EmitDefaultValue=false)]

        [DefaultValue("Mediacom Cable")]

        public string ISP { get; set; } = "Mediacom Cable";

        /// <summary>
        /// Gets or Sets Organization
        /// </summary>
        /* <example>Mediacom Cable</example> */

        [DataMember(Name="organization", EmitDefaultValue=false)]

        [DefaultValue("Mediacom Cable")]

        public string Organization { get; set; } = "Mediacom Cable";

        /// <summary>
        /// Gets or Sets ASN
        /// </summary>
        /* <example>30036</example> */

        [DataMember(Name="ASN", EmitDefaultValue=true)]

        [DefaultValue(30036)]

        public int ASN { get; set; } = 30036;

        /// <summary>
        /// Gets or Sets Host
        /// </summary>
        /* <example>192-0-2-110.client.mchsi.com</example> */

        [DataMember(Name="host", EmitDefaultValue=false)]

        [DefaultValue("192-0-2-110.client.mchsi.com")]

        public string Host { get; set; } = "192-0-2-110.client.mchsi.com";

        /// <summary>
        /// Gets or Sets CountryCode
        /// </summary>
        /* <example>US</example> */

        [DataMember(Name="countryCode", EmitDefaultValue=false)]

        [DefaultValue("US")]

        public string CountryCode { get; set; } = "US";

        /// <summary>
        /// Gets or Sets City
        /// </summary>
        /* <example>Houston</example> */

        [DataMember(Name="city", EmitDefaultValue=false)]

        [DefaultValue("Houston")]

        public string City { get; set; } = "Houston";

        /// <summary>
        /// Gets or Sets Region
        /// </summary>
        /* <example>Texas</example> */

        [DataMember(Name="region", EmitDefaultValue=false)]

        [DefaultValue("Texas")]

        public string Region { get; set; } = "Texas";

        /// <summary>
        /// Gets or Sets IsCrawler
        /// </summary>
        /* <example>false</example> */

        [DataMember(Name="isCrawler", EmitDefaultValue=true)]

        [DefaultValue(false)]

        public bool IsCrawler { get; set; } = false;

        /// <summary>
        /// Gets or Sets Latitude
        /// </summary>
        /* <example>29.7079</example> */

        [DataMember(Name="latitude", EmitDefaultValue=true)]

        [DefaultValue(29.7079)]

        public double Latitude { get; set; } = 29.7079;

        /// <summary>
        /// Gets or Sets Longitude
        /// </summary>
        /* <example>-95.401</example> */

        [DataMember(Name="longitude", EmitDefaultValue=true)]

        [DefaultValue(-95.401)]

        public double Longitude { get; set; } = -95.401;

        /// <summary>
        /// Gets or Sets ZipCode
        /// </summary>
        /* <example>77001</example> */

        [DataMember(Name="zipCode", EmitDefaultValue=false)]

        [DefaultValue("77001")]

        public string ZipCode { get; set; } = "77001";

        /// <summary>
        /// Gets or Sets Timezone
        /// </summary>
        /* <example>America Matamoros</example> */

        [DataMember(Name="timezone", EmitDefaultValue=false)]

        [DefaultValue("America Matamoros")]

        public string Timezone { get; set; } = "America Matamoros";

        /// <summary>
        /// Gets or Sets Vpn
        /// </summary>
        /* <example>false</example> */

        [DataMember(Name="vpn", EmitDefaultValue=true)]

        [DefaultValue(false)]

        public bool Vpn { get; set; } = false;

        /// <summary>
        /// Gets or Sets Tor
        /// </summary>
        /* <example>false</example> */

        [DataMember(Name="tor", EmitDefaultValue=true)]

        [DefaultValue(false)]

        public bool Tor { get; set; } = false;

        /// <summary>
        /// Gets or Sets ActiveVpn
        /// </summary>
        /* <example>false</example> */

        [DataMember(Name="activeVpn", EmitDefaultValue=true)]

        [DefaultValue(false)]

        public bool ActiveVpn { get; set; } = false;

        /// <summary>
        /// Gets or Sets ActiveTor
        /// </summary>
        /* <example>false</example> */

        [DataMember(Name="activeTor", EmitDefaultValue=true)]

        [DefaultValue(false)]

        public bool ActiveTor { get; set; } = false;

        /// <summary>
        /// Gets or Sets RecentAbuse
        /// </summary>
        /* <example>true</example> */

        [DataMember(Name="recentAbuse", EmitDefaultValue=true)]

        [DefaultValue(true)]

        public bool RecentAbuse { get; set; } = true;

        /// <summary>
        /// Gets or Sets BotStatus
        /// </summary>
        /* <example>false</example> */

        [DataMember(Name="botStatus", EmitDefaultValue=true)]

        [DefaultValue(false)]

        public bool BotStatus { get; set; } = false;

        /// <summary>
        /// Gets or Sets Mobile
        /// </summary>
        /* <example>false</example> */

        [DataMember(Name="mobile", EmitDefaultValue=true)]

        [DefaultValue(false)]

        public bool Mobile { get; set; } = false;

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            var sb = new StringBuilder();
            sb.Append("class ProxyAndVpnDetectionResponse {\n");
            sb.Append("  Message: ").Append(Message).Append("\n");
            sb.Append("  Success: ").Append(Success).Append("\n");
            sb.Append("  FraudScore: ").Append(FraudScore).Append("\n");
            sb.Append("  Proxy: ").Append(Proxy).Append("\n");
            sb.Append("  ISP: ").Append(ISP).Append("\n");
            sb.Append("  Organization: ").Append(Organization).Append("\n");
            sb.Append("  ASN: ").Append(ASN).Append("\n");
            sb.Append("  Host: ").Append(Host).Append("\n");
            sb.Append("  CountryCode: ").Append(CountryCode).Append("\n");
            sb.Append("  City: ").Append(City).Append("\n");
            sb.Append("  Region: ").Append(Region).Append("\n");
            sb.Append("  IsCrawler: ").Append(IsCrawler).Append("\n");
            sb.Append("  Latitude: ").Append(Latitude).Append("\n");
            sb.Append("  Longitude: ").Append(Longitude).Append("\n");
            sb.Append("  ZipCode: ").Append(ZipCode).Append("\n");
            sb.Append("  Timezone: ").Append(Timezone).Append("\n");
            sb.Append("  Vpn: ").Append(Vpn).Append("\n");
            sb.Append("  Tor: ").Append(Tor).Append("\n");
            sb.Append("  ActiveVpn: ").Append(ActiveVpn).Append("\n");
            sb.Append("  ActiveTor: ").Append(ActiveTor).Append("\n");
            sb.Append("  RecentAbuse: ").Append(RecentAbuse).Append("\n");
            sb.Append("  BotStatus: ").Append(BotStatus).Append("\n");
            sb.Append("  Mobile: ").Append(Mobile).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }

        /// <summary>
        /// Returns the JSON string presentation of the object
        /// </summary>
        /// <returns>JSON string presentation of the object</returns>
        public string ToJson()
        {
            return JsonConvert.SerializeObject(this, Formatting.Indented);
        }

        /// <summary>
        /// Returns true if objects are equal
        /// </summary>
        /// <param name="obj">Object to be compared</param>
        /// <returns>Boolean</returns>
        public override bool Equals(object obj)
        {
            if (obj is null) return false;
            if (ReferenceEquals(this, obj)) return true;
            return obj.GetType() == GetType() && Equals((ProxyAndVpnDetectionResponse)obj);
        }

        /// <summary>
        /// Returns true if ProxyAndVpnDetectionResponse instances are equal
        /// </summary>
        /// <param name="other">Instance of ProxyAndVpnDetectionResponse to be compared</param>
        /// <returns>Boolean</returns>
        public bool Equals(ProxyAndVpnDetectionResponse other)
        {
            if (other is null) return false;
            if (ReferenceEquals(this, other)) return true;

            return 
                (
                    Message == other.Message ||
                    Message != null &&
                    Message.Equals(other.Message)
                ) && 
                (
                    Success == other.Success ||
                    
                    Success.Equals(other.Success)
                ) && 
                (
                    FraudScore == other.FraudScore ||
                    
                    FraudScore.Equals(other.FraudScore)
                ) && 
                (
                    Proxy == other.Proxy ||
                    
                    Proxy.Equals(other.Proxy)
                ) && 
                (
                    ISP == other.ISP ||
                    ISP != null &&
                    ISP.Equals(other.ISP)
                ) && 
                (
                    Organization == other.Organization ||
                    Organization != null &&
                    Organization.Equals(other.Organization)
                ) && 
                (
                    ASN == other.ASN ||
                    
                    ASN.Equals(other.ASN)
                ) && 
                (
                    Host == other.Host ||
                    Host != null &&
                    Host.Equals(other.Host)
                ) && 
                (
                    CountryCode == other.CountryCode ||
                    CountryCode != null &&
                    CountryCode.Equals(other.CountryCode)
                ) && 
                (
                    City == other.City ||
                    City != null &&
                    City.Equals(other.City)
                ) && 
                (
                    Region == other.Region ||
                    Region != null &&
                    Region.Equals(other.Region)
                ) && 
                (
                    IsCrawler == other.IsCrawler ||
                    
                    IsCrawler.Equals(other.IsCrawler)
                ) && 
                (
                    Latitude == other.Latitude ||
                    
                    Latitude.Equals(other.Latitude)
                ) && 
                (
                    Longitude == other.Longitude ||
                    
                    Longitude.Equals(other.Longitude)
                ) && 
                (
                    ZipCode == other.ZipCode ||
                    ZipCode != null &&
                    ZipCode.Equals(other.ZipCode)
                ) && 
                (
                    Timezone == other.Timezone ||
                    Timezone != null &&
                    Timezone.Equals(other.Timezone)
                ) && 
                (
                    Vpn == other.Vpn ||
                    
                    Vpn.Equals(other.Vpn)
                ) && 
                (
                    Tor == other.Tor ||
                    
                    Tor.Equals(other.Tor)
                ) && 
                (
                    ActiveVpn == other.ActiveVpn ||
                    
                    ActiveVpn.Equals(other.ActiveVpn)
                ) && 
                (
                    ActiveTor == other.ActiveTor ||
                    
                    ActiveTor.Equals(other.ActiveTor)
                ) && 
                (
                    RecentAbuse == other.RecentAbuse ||
                    
                    RecentAbuse.Equals(other.RecentAbuse)
                ) && 
                (
                    BotStatus == other.BotStatus ||
                    
                    BotStatus.Equals(other.BotStatus)
                ) && 
                (
                    Mobile == other.Mobile ||
                    
                    Mobile.Equals(other.Mobile)
                );
        }

        /// <summary>
        /// Gets the hash code
        /// </summary>
        /// <returns>Hash code</returns>
        public override int GetHashCode()
        {
            unchecked // Overflow is fine, just wrap
            {
                var hashCode = 41;
                // Suitable nullity checks etc, of course :)
                    if (Message != null)
                    hashCode = hashCode * 59 + Message.GetHashCode();
                    
                    hashCode = hashCode * 59 + Success.GetHashCode();
                    
                    hashCode = hashCode * 59 + FraudScore.GetHashCode();
                    
                    hashCode = hashCode * 59 + Proxy.GetHashCode();
                    if (ISP != null)
                    hashCode = hashCode * 59 + ISP.GetHashCode();
                    if (Organization != null)
                    hashCode = hashCode * 59 + Organization.GetHashCode();
                    
                    hashCode = hashCode * 59 + ASN.GetHashCode();
                    if (Host != null)
                    hashCode = hashCode * 59 + Host.GetHashCode();
                    if (CountryCode != null)
                    hashCode = hashCode * 59 + CountryCode.GetHashCode();
                    if (City != null)
                    hashCode = hashCode * 59 + City.GetHashCode();
                    if (Region != null)
                    hashCode = hashCode * 59 + Region.GetHashCode();
                    
                    hashCode = hashCode * 59 + IsCrawler.GetHashCode();
                    
                    hashCode = hashCode * 59 + Latitude.GetHashCode();
                    
                    hashCode = hashCode * 59 + Longitude.GetHashCode();
                    if (ZipCode != null)
                    hashCode = hashCode * 59 + ZipCode.GetHashCode();
                    if (Timezone != null)
                    hashCode = hashCode * 59 + Timezone.GetHashCode();
                    
                    hashCode = hashCode * 59 + Vpn.GetHashCode();
                    
                    hashCode = hashCode * 59 + Tor.GetHashCode();
                    
                    hashCode = hashCode * 59 + ActiveVpn.GetHashCode();
                    
                    hashCode = hashCode * 59 + ActiveTor.GetHashCode();
                    
                    hashCode = hashCode * 59 + RecentAbuse.GetHashCode();
                    
                    hashCode = hashCode * 59 + BotStatus.GetHashCode();
                    
                    hashCode = hashCode * 59 + Mobile.GetHashCode();
                return hashCode;
            }
        }

        #region Operators
        #pragma warning disable 1591

        public static bool operator ==(ProxyAndVpnDetectionResponse left, ProxyAndVpnDetectionResponse right)
        {
            return Equals(left, right);
        }

        public static bool operator !=(ProxyAndVpnDetectionResponse left, ProxyAndVpnDetectionResponse right)
        {
            return !Equals(left, right);
        }

        #pragma warning restore 1591
        #endregion Operators
    }
}